### ISSUE TITLE
File names are not sanitised and no random string is added + double file ext

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/storage#20]
@BrettRToomey 
I think I know why we got the 505 error 

The path is 
vapor-sandbox/test/Screen Shot 2016-12-20 at 16.21.01.png.png

in my ex

In the old packages there was a some code to keep some of the file name but to add random + timestamp and max length of 255 for full path, so it can be saved in a db

Here we also have double file ext
with a simpler file name we still end up like this
vapor-sandbox/test/test.png.png

now we go a different error

badResponse(Response
- HTTP/1.1 301 Moved Permanently
- Headers:
	Connection: close
	Transfer-Encoding: chunked
	Server: AmazonS3
	x-amz-bucket-region: eu-west-1
	x-amz-request-id: [REMOVED]
	x-amz-id-2: [REMOVED]
	Content-Type: application/xml
	Date: Fri, 23 Dec 2016 11:44:56 GMT
- Body:
	<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>PermanentRedirect</Code><Message>The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.</Message><Bucket>[REMOVED]</Bucket><Endpoint>[REMOVED]</Endpoint><RequestId>[REMOVED]</RequestId><HostId>[REMOVED]=</HostId></Error>)

Also what should the filter be for the nodes syntax?
Tried     "template": "vapor-sandbox/$mimeFolder/$folder/$file"
gave me: vapor-sandbox/image/png/test/test.png.png

we need "images/original" : "data" part to work also

**Comment by BrettRToomey** [comment]
@Casperhr 
Okay, I have everything done except for one. For your custom things like a random string and timestamp I can add an alias for both of those. We can also add a max file path length in the configuration. Would that work for you?

Example:
```
/$fileName_$timestamp_$random.$fileExtension
```
would return something like:
```
/test_30-12-2016_5wokWpw2qfn.png
```

Keep in mind that's just an example, the date can be in any standard you want. I guess I could even open up a day/month/year alias, too.
