### ISSUE TITLE
CDN path builder

### ISSUE THREAD

**Issue by BrettRToomey** [nodes-vapor/storage#25]
We can make the default behavior baseURL + path, but I'll make an optional closure in the `Storage` struct that would look something like this

```swift
var cdnPathBuilder: ((baseURL: String, path: String) -> String)?
```

Then you can set it and change the default behavior.

Example:
```swift
Storage.cdnPathbuilder = { baseURL, path in
    return baseURL + "/hi" + path
}
```

**Comment by Casperhr** [comment]
Looks like a smart way of doing it!

Then just make a readme for the nodes one.
