### ISSUE TITLE
Missing file / type on some images

### ISSUE THREAD

**Issue by Casperhr** [nodes-vapor/storage#32]
![29985909096_d7e2bba688_b](https://cloud.githubusercontent.com/assets/1279756/22654994/e9393990-ec8e-11e6-89d5-67e53782ef82.jpg)

**Comment by Casperhr** [comment]
filePath = try Storage.upload(formData: assetUnwrapped, folder: "messages")

**Comment by BrettRToomey** [comment]
Fixed #32
