### ISSUE TITLE
Implement `get` and `delete` in the S3 driver 

### ISSUE THREAD

**Issue by BrettRToomey** [nodes-vapor/storage#47]

**Comment by kasperwelner** [comment]
I spent an hour trying to figure out why I got an empty response for my file before I realised that this very essential feature is not implemented. The library returns empty data, even though it's documented as working. Maybe consider throwing a `fatalError` or similar to not mislead consumers of the API.

**Comment by siemensikkema** [comment]
@kasperwelner Sorry about that! I've addressed it in #64

**Comment by MattiasBowallius** [comment]
Hi! I have an implementation of the get function that I'm willing to create a pull request for if you want it :)

**Comment by siemensikkema** [comment]
@MattiasBowallius PRs are very welcome! 😃

**Comment by MattiasBowallius** [comment]
Unfortunately I don't have enough access rights to create a branch and therefore a PR :)

**Comment by siemensikkema** [comment]
@MattiasBowallius Ah, the way to get around that is to fork it and create PR, a new branch there and then PR from there into this repo 🙂
