### ISSUE TITLE
Issue with S3 amzDate

### ISSUE THREAD

**Issue by chili-ios** [nodes-vapor/storage#51]
Hey guys,

Yesterday I've started receiving `requestTimeTooSkewed` errors from S3.
After spending a few hours on the investigation I've found that wrong date format is used for `amzDate`. Instead of `YYYY` should be `yyyy` as `YYYY` is ISO-8601 week year and it started to return 2019 from yesterday. 

Example from playground:
![image](https://user-images.githubusercontent.com/19732707/50563968-ed71f700-0d29-11e9-9ddb-f6debea9a145.png)

**Comment by BrettRToomey** [comment]
Thanks a lot for the detailed report!

**Comment by chili-ios** [comment]
Great! Thanks for the quick fix.
